---
- name: uni  deploy v3 contract
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - ../config.yml
    - ../../uni-contract-deploy/contract_address.yaml
  tasks:
  ###############################################################################################################
    - name: delete the constract state.json
      shell: rm -rf state.json
      become: yes
      become_method: sudo
    - name: yarn install
      shell: yarn install
      become: yes
      become_method: sudo
    - name: deploy uniswap v3 constracts.
      shell: yarn start -pk {{ hex_private_key }} -j {{ node_address }} -w9 {{ WETH }} -v2  {{ UniswapV2Factory }} -o  {{ hex_pub_address }} -s  ./state.json -ncl AT -c 0 
      become: yes
      become_method: sudo
    - name: delete and create the constract_address.yaml
      shell: rm -rf  ../contract_address.yaml && touch  ../contract_address.yaml 
      become: yes
      become_method: sudo
    - name: copy the state.json file 
      shell: cp state.json ../contract_address.yaml
      become: yes
      become_method: sudo

