version: '3'

services:
  uni-interface:
    image: nginx:latest
    container_name: uni-interface
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - "8511:80"
    restart: on-failure