---
- name: start explorer
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  ###############################################################################################################
    - name: explorer  shutdown
  #    shell: "docker run -p {{ localport }}:80 -e APP_NODE_URL={{ eth_rpc }} alethio/ethereum-lite-explorer"
      shell: "docker-compose -f ./templates/docker-compose.yml down"
    - name:  explorer  start
      shell: "docker-compose -f ./templates/docker-compose.yml up -d"
