version: '2'

services:
  bft_node1:
    container_name: bft_node1
    image: nervos/muta:dev
    hostname: bft_node1
    environment:
      - RUST_LOG
      - RUST_BACKTRACE
    volumes:
      - ~/tmp/muta-devops/muta:/app
      - ./configs/1.toml:/app/devtools/chain/config.toml
      - ~/tmp/muta-devops/chain-data/7c04ff3-004-20191216_104611/data/1:/data
      - ~/tmp/muta-devops/chain-data/7c04ff3-004-20191216_104611/logs/1:/logs
      - ~/tmp/muta-devops/muta/target/release/muta-chain-7c04ff3:/app/muta-chain
    networks:
      chaos:
        aliases:
          - bft_node1
        ipv4_address: 174.20.0.101
    command: |
      sh -c '
      cd /app;
      ./muta-chain;'
  bft_node2:
    container_name: bft_node2
    image: nervos/muta:dev
    hostname: bft_node2
    environment:
      - RUST_LOG
      - RUST_BACKTRACE
    volumes:
      - ~/tmp/muta-devops/muta:/app
      - ./configs/2.toml:/app/devtools/chain/config.toml
      - ~/tmp/muta-devops/chain-data/7c04ff3-004-20191216_104611/data/2:/data
      - ~/tmp/muta-devops/chain-data/7c04ff3-004-20191216_104611/logs/2:/logs
      - ~/tmp/muta-devops/muta/target/release/muta-chain-7c04ff3:/app/muta-chain
    networks:
      chaos:
        aliases:
          - bft_node2
        ipv4_address: 174.20.0.102
    command: |
      sh -c '
      cd /app;
      ./muta-chain;'
  bft_node3:
    container_name: bft_node3
    image: nervos/muta:dev
    hostname: bft_node3
    environment:
      - RUST_LOG
      - RUST_BACKTRACE
    volumes:
      - ~/tmp/muta-devops/muta:/app
      - ./configs/3.toml:/app/devtools/chain/config.toml
      - ~/tmp/muta-devops/chain-data/7c04ff3-004-20191216_104611/data/3:/data
      - ~/tmp/muta-devops/chain-data/7c04ff3-004-20191216_104611/logs/3:/logs
      - ~/tmp/muta-devops/muta/target/release/muta-chain-7c04ff3:/app/muta-chain
    networks:
      chaos:
        aliases:
          - bft_node3
        ipv4_address: 174.20.0.103
    command: |
      sh -c '
      cd /app;
      ./muta-chain;'
  bft_node4:
    container_name: bft_node4
    image: nervos/muta:dev
    hostname: bft_node4
    environment:
      - RUST_LOG
      - RUST_BACKTRACE
    volumes:
      - ~/tmp/muta-devops/muta:/app
      - ./configs/4.toml:/app/devtools/chain/config.toml
      - ~/tmp/muta-devops/chain-data/7c04ff3-004-20191216_104611/data/4:/data
      - ~/tmp/muta-devops/chain-data/7c04ff3-004-20191216_104611/logs/4:/logs
      - ~/tmp/muta-devops/muta/target/release/muta-chain-7c04ff3:/app/muta-chain
    networks:
      chaos:
        aliases:
          - bft_node4
        ipv4_address: 174.20.0.104
    command: |
      sh -c '
      cd /app;
      ./muta-chain;'

networks:
  chaos:
    ipam:
     config:
       - subnet: 174.20.0.0/24