---
- name: all in one
  hosts: muta-dev
  user: muta
  vars:
    devops_path: "/home/muta/muta-devops"
    muta_path: "{{ devops_path }}/muta"
    configs_path: "{{ devops_path }}/configs"
    data_dir: "{{ devops_path }}/chain-data"
    muta_version: eb73210
    muta_repo: https://github.com/KaoImin/muta.git
    chain_node_num: 4
    bootstraps_num: "{{ chain_node_num }}"
    force_recreate: false
  vars_files:
    - chain_meta.json
  tasks:
    - include_tasks: init_server.yml
    - include_tasks: init_project.yml
    - include_tasks: start_chain.yml